local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>ff', function() builtin.find_files({hidden = true}) end, {})
vim.keymap.set('n', '<leader>fdf', function() builtin.find_files({hidden = true, search_dirs = {vim.fn.input("Directory > ")}}) end, {})
vim.keymap.set('n', '<leader>fg', builtin.git_files, {})
vim.keymap.set('n', '<leader>gf', function()
	builtin.grep_string({ search = vim.fn.input("Grep > ") })
end)
vim.keymap.set('n', '<leader>gg', function()
	builtin.grep_string({ search = vim.fn.input("Grep > "), search_dirs = builtin.git_files()})
end)
vim.keymap.set('n', '<leader>fdw', function()
	builtin.grep_string({ search = vim.fn.input("Grep > ") , search_dirs = {vim.fn.input("Directory > ")}})
end)
vim.keymap.set('n', '<leader>ft', builtin.grep_string, {})
vim.keymap.set('n', '<leader>vh', builtin.help_tags, {})

